name: AUR CI
description: Continuous integration for AUR packages
author: Sergey Kanafyev

branding:
  icon: check-circle
  color: blue

inputs:
  github-token:
    description: GitHub token for creating releases
    required: false
    default: ${{ github.token }}

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
